name: Check GitHub Workflows

on:
  pull_request:
    paths:
      - .github/workflows/**/*.yaml
      - .github/workflows/check-github-workflows.yaml
  push:
    paths:
      - .github/workflows/**/*.yaml
      - .github/workflows/check-github-workflows.yaml

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check Syntax
        # Disable shellcheck since it's installed on CI but maybe not on user machine,
        # which can cause very confusing debugging issues.
        run: go run github.com/rhysd/actionlint/cmd/actionlint@v1.7.4 -shellcheck=
