name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-22.04
          - windows-2022
        go:
          - ""
        include:
          - os: ubuntu-22.04
            go: stable
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ !matrix.go && 'go.work' || '' }}
          go-version: ${{ matrix.go }}
          cache-dependency-path: |
            **/go.sum
            versions.go

      - name: run lints
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run build -v lint

      - name: run tests
        run: go run build -v test
